### ISSUE TITLE
About trainning

### ISSUE THREAD

**Issue by shz1314** [csxmli2016/GFRNet#1]
Hi，
  I want to follow your work. Shall you give the training datasets or the training method??Very thanks.
Yours Haoze

**Comment by csxmli2016** [comment]
Sorry, we may cooperate with other company, so it is not convenient to share the training code.  As for the introduction of dataset or method, you can find them in our paper. I will release all the related materials after getting permission.

**Comment by shz1314** [comment]
Hi，
  Thanks all the same. Just the datasets or the code of degradation model is ok.  Very thanks.
Yours Haoze

**Comment by shz1314** [comment]
If convenient, send me to the email haoze_song_jnu@163.com

**Comment by csxmli2016** [comment]
The rules for selecting image pairs are described in details in our papar, you can select them from WebFace by yourself. 
As for the degradation model, it is very simple. Please refer to [torch image package](https://github.com/torch/image) carefully. The degradation parameter can also be found in our paper.
Any question, please contact me.

**Comment by shz1314** [comment]
hi,
  Shall you send me the code to degrade the image. I have followed paper to code, but i have never used lua, so i meet many errors. It bored me several days. Please send to me. So thanks

**Comment by csxmli2016** [comment]
What error? I think scale, noise, and jpeg is simple. As for gaussian blur , you can use image.gaussian to obtain kernel and then image.convolve or nn.SpatialConvolution with known kernel should be applied to image. Otherwise, I have no idea which problem you can meet.
