### ISSUE TITLE
how to install stn？

### ISSUE THREAD

**Issue by shz1314** [csxmli2016/GFRNet#2]
hi，
  module 'stn' not found:No LuaRocks module found for stn

**Comment by csxmli2016** [comment]
See the stn link in Section [Requirements and Dependencies](https://github.com/csxmli2016/GFRNet#requirements-and-dependencies)

**Comment by shz1314** [comment]
I meet the new problem 


/home/song/torch/install/bin/luajit: /home/song/torch/install/share/lua/5.1/threads/threads.lua:315: /home/song/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /home/song/torch/install/share/lua/5.1/image/init.lua:367: /home/song/下载/GFRNet-master/Datasets/IMDB/2.jp/home/song/下载/GFRNet-master/Datasets/IMDB/1.jp/home/song/下载/GFRNet-master/Datasets/IMDB/3.jpg: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/song/torch/install/share/lua/5.1/image/init.lua:367: in function 'load'
	/home/song/下载/GFRNet-master/data2/donkey_folderC.lua:151: in function 'loadImage'
	/home/song/下载/GFRNet-master/data2/donkey_folderC.lua:205: in function 'sampleHookTrain'
	/home/song/下载/GFRNet-master/data2/dataset.lua:341: in function 'getByClass'
	/home/song/下载/GFRNet-master/data2/dataset.lua:376: in function </home/song/下载/GFRNet-master/data2/dataset.lua:367>
	[C]: in function 'xpcall'
	/home/song/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	/home/song/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/song/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/home/song/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk

**Comment by CastellanLiu** [comment]
/home/song/下载/GFRNet-master/Datasets/IMDB/2.jp/home/song/下载/GFRNet-master/Datasets/IMDB/1.jp/home/song/下载/GFRNet-master/Datasets/IMDB/3.jpg
Obviously it's not a valid path, maybe remove the chinese characters will help.
BTW, how did you modify "opt.phase" in test.lua?

**Comment by shz1314** [comment]
opt = {
    DATA_ROOT = './Datasets',   --DataRoot
    batchSize = 1,            -- # images in batch
    loadSize = 256,           -- scale images to this size
    fineSize = 256,           --  then crop to this size
    flip=0,                   -- horizontal mirroring data augmentation
    gpu = 1,                  -- gpu = 0 is CPU mode. gpu=X is GPU mode on GPU X (cpu untested)
    which_direction = 'AtoB', -- AtoB or BtoA
    phase = 'IMDB',            -- test dataset name
    preprocess = 'regular',   -- for special purpose preprocessing, e.g., for colorization, change this (selects preprocessing functions in util.lua)
    aspect_ratio = 1.0,       -- aspect ratio of result images
    name = 'FaceRestoration',                -- name of experiment, selects which model to run, should generally should be passed on command line
    input_nc = 3,             -- #  of input image channels
    output_nc = 3,            -- #  of output image channels
    serial_batches = 1,       -- if 1, takes images in order to make batches, otherwise takes them randomly
    serial_batch_iter = 1,    -- iter into serial image list
    cudnn = 0,                -- set to 0 to not use cudnn (untested)
    checkpoints_dir = './checkpoints', -- loads models from here
    results_dir='./results',          -- saves results here
    which_model = 'netG',            -- which epoch to test? 

}

**Comment by CastellanLiu** [comment]
Just place the whole folder into a path without Chinese characters and try again, if the problem occurs again, then I have no idea about it.

**Comment by shz1314** [comment]
solved！  Very thanks!  Help me a lot !
