### ISSUE TITLE
About training and test dataset text list

### ISSUE THREAD

**Issue by BostonLobster** [csxmli2016/GFRNet#4]
Hi, author. Could you please release your training and test dataset text list?
The training text list I mean is something like this:
`n001110/0263_01.jpg -->n001110/0128_01.jpg`
with the first item indicating the example image and the second indicating the training image.

I know you describe how to construct the training and test dataset detailedly. But there are a lot of variations since VGGFace2 is a huge dataset. Since I want to exactly reproduce your experiment, so I think the training and test text list you used are needed. (Also, if you don't want I compare with your method at a lower result.)

**Comment by csxmli2016** [comment]
Hi,
We will release all the data after the expiration of contract period.
