### ISSUE TITLE
Pytorch implementation of WarpNet is NOT found

### ISSUE THREAD

**Issue by BostonLobster** [csxmli2016/GFRNet#5]
The link you provide for Pytorch implementation of WarpNet is not found. Please check it.

**Comment by csxmli2016** [comment]
Hi, 

Sorry for this mistake. I closed this repository since it is still in the period of contract.

**Comment by YancyChao** [comment]
> Hi,
> 
> Sorry for this mistake. I closed this repository since it is still in the period of contract.

Hi, is it possible to open source a pytorch implementation of warpnet?

**Comment by csxmli2016** [comment]
> > Hi,
> > Sorry for this mistake. I closed this repository since it is still in the period of contract.
> 
> Hi, is it possible to open source a pytorch implementation of warpnet?

I have invited you as a collaborator on the repository.
